/**
 * main.js — entry point + UI orchestration
 *
 * Five interaction layers that together make the UI feel reactive:
 *
 *   1. Mouse parallax    — renderer tilts the scene as the mouse moves (renderer.js)
 *   2. Magnetic buttons  — nav buttons attract the cursor and snap back elastically
 *   3. Char stagger      — each letter in a button waves independently on hover
 *   4. Post-fx on switch — bloom + chroma spike on mode transition then settle
 *   5. GSAP timeline     — mode switch is a choreographed sequence, not parallel fades
 */

import { gsap }                from 'gsap'
import { Renderer }            from './core/renderer.js'
import { LissajousMode }       from './modes/lissajous.js'
import { FourierMode }         from './modes/fourier.js'
import { RoseMode }            from './modes/rose.js'
import { ChaosMode }           from './modes/chaos.js'
import { MandelbrotMode }      from './modes/mandelbrot.js'
import { PendulumMode }        from './modes/pendulum.js'
import { NewtonMode }          from './modes/newton.js'
import { GrayScottMode }       from './modes/grayscott.js'
import { JuliaMode }           from './modes/julia.js'
import { BackgroundParticles } from './core/particles.js'
import { AudioReactive }       from './core/audio.js'

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

const renderer = new Renderer()
let   prevTime = performance.now()

// Background curl-noise particle field (lives in the main scene)
const particles = new BackgroundParticles(renderer.scene)

// Audio reactive analyser
const audio = new AudioReactive()

let activeMode    = new LissajousMode(renderer.scene, renderer)
activeMode.setAudio?.(audio)
let transitioning = false

const overlay = document.getElementById('transition-overlay')

const MODE_META = {
  lissajous: {
    title: 'Lissajous',
    equation: 'x = A sin(at + delta)',
    description: 'A luminous parametric orbit drawn as a living trail.',
  },
  fourier: {
    title: 'Fourier',
    equation: 'f(t) = sum A_n sin(nwt)',
    description: 'Rotating phasors assemble waves from simple circular motion.',
  },
  rose: {
    title: 'Rose Curves',
    equation: 'r = cos(k theta)',
    description: 'Petal symmetries unfold from polar rhythm and phase.',
  },
  mandelbrot: {
    title: 'Mandelbrot',
    equation: 'z = z^2 + c',
    description: 'A self-similar frontier generated by one repeated question.',
  },
  julia: {
    title: 'Julia',
    equation: 'z = z^2 + c',
    description: 'Complex constants become living fingerprints of iteration.',
  },
  newton: {
    title: "Newton's Fractal",
    equation: "z = z - f(z) / f'(z)",
    description: 'Basins of attraction reveal where each guess finally lands.',
  },
  chaos: {
    title: 'Attractors',
    equation: 'dx/dt = sigma(y - x)',
    description: 'Deterministic equations braid paths that never repeat.',
  },
  pendulum: {
    title: 'Double Pendulum',
    equation: 'theta\'\' = F(theta, omega)',
    description: 'Coupled motion turns tiny differences into sweeping trails.',
  },
  grayscott: {
    title: 'Gray-Scott',
    equation: 'u_t = D laplace u - uv^2 + f(1-u)',
    description: 'Reaction and diffusion negotiate spots, stripes, and cells.',
  },
}

const modeReveal = {
  root:        document.getElementById('mode-reveal'),
  title:       document.getElementById('mode-title'),
  equation:    document.getElementById('mode-equation'),
  description: document.getElementById('mode-description'),
}

const modeNote = {
  title:       document.getElementById('note-title'),
  equation:    document.getElementById('note-equation'),
  description: document.getElementById('note-description'),
}

const hud = {
  mode:       document.getElementById('hud-mode'),
  equation:   document.getElementById('hud-equation'),
  audio:      document.getElementById('hud-audio'),
  fps:        document.getElementById('hud-fps'),
  controlsHandle: document.getElementById('controls-handle'),
  controls:   document.getElementById('controls-btn'),
  analytics:  document.getElementById('analytics-btn'),
  pause:      document.getElementById('pause-btn'),
  capture:    document.getElementById('capture-btn'),
  fullscreen: document.getElementById('fullscreen-btn'),
  toast:      document.getElementById('toast'),
}

const analyticsPanel = document.getElementById('analytics-panel')
const analytics = {
  mode:     document.getElementById('analytics-mode'),
  fps:      document.getElementById('analytics-fps'),
  frame:    document.getElementById('analytics-frame'),
  draws:    document.getElementById('analytics-draws'),
  geo:      document.getElementById('analytics-geo'),
  scene:    document.getElementById('analytics-scene'),
  camera:   document.getElementById('analytics-camera'),
  pointer:  document.getElementById('analytics-pointer'),
  audio:    document.getElementById('analytics-audio'),
  bloom:    document.getElementById('analytics-bloom'),
  viewport: document.getElementById('analytics-viewport'),
}

let paused = false
let controlsVisible = true
let analyticsVisible = false
let toastTween = null
let fpsSampleTime = performance.now()
let fpsFrames = 0
let currentFps = 0
let analyticsSampleTime = performance.now()

function setModeChrome(name, reveal = false) {
  const meta = MODE_META[name] ?? MODE_META.lissajous
  document.body.dataset.mode = name

  modeReveal.title.textContent = meta.title
  modeReveal.equation.textContent = meta.equation
  modeReveal.description.textContent = meta.description
  modeNote.title.textContent = meta.title
  modeNote.equation.textContent = meta.equation
  modeNote.description.textContent = meta.description
  hud.mode.textContent = meta.title
  hud.equation.textContent = meta.equation
  analytics.mode.textContent = meta.title

  if (!reveal) return

  gsap.killTweensOf(modeReveal.root)
  gsap.timeline()
    .set(modeReveal.root, { opacity: 0, y: 18, scale: 0.985 })
    .to(modeReveal.root, { opacity: 1, y: 0, scale: 1, duration: 0.34, ease: 'power3.out' }, 0.02)
    .to(modeReveal.root, { opacity: 0, y: -14, scale: 1.01, duration: 0.42, ease: 'power2.in' }, 1.05)
}

function updateAudioChrome() {
  hud.audio.textContent = audio.enabled ? 'Audio on' : 'Audio off'
  hud.audio.classList.toggle('active', audio.enabled)
}

function showToast(message) {
  hud.toast.textContent = message
  if (toastTween) toastTween.kill()
  toastTween = gsap.timeline()
    .to(hud.toast, { opacity: 1, y: 0, duration: 0.22, ease: 'power2.out' })
    .to(hud.toast, { opacity: 0, y: 8, duration: 0.28, ease: 'power2.in' }, '+=1.9')
}

function setControlsVisible(next) {
  controlsVisible = next
  document.body.classList.toggle('controls-hidden', !controlsVisible)
  hud.controls.classList.toggle('active', controlsVisible)
  hud.controlsHandle.textContent = controlsVisible ? 'Controls' : 'Show controls'
  hud.controls.setAttribute('aria-label', controlsVisible ? 'Hide controls' : 'Show controls')
  hud.controls.setAttribute('title', controlsVisible ? 'Hide controls' : 'Show controls')
  hud.controlsHandle.setAttribute('aria-label', controlsVisible ? 'Hide controls' : 'Show controls')
  hud.controlsHandle.setAttribute('title', controlsVisible ? 'Hide controls' : 'Show controls')
  positionControlPane()
}

function setAnalyticsVisible(next) {
  analyticsVisible = next
  analyticsPanel.classList.toggle('open', analyticsVisible)
  hud.analytics.classList.toggle('active', analyticsVisible)
  hud.analytics.setAttribute('aria-label', analyticsVisible ? 'Hide analytics' : 'Show analytics')
  hud.analytics.setAttribute('title', analyticsVisible ? 'Hide analytics' : 'Show analytics')
}

function formatVec3(v) {
  return `${v.x.toFixed(1)}, ${v.y.toFixed(1)}, ${v.z.toFixed(1)}`
}

function positionControlPane() {
  const panes = document.querySelectorAll('.tp-dfwv')
  panes.forEach(pane => {
    Object.assign(pane.style, {
      position: 'fixed',
      top: window.innerWidth <= 760 ? '76px' : '126px',
      right: window.innerWidth <= 760 ? '12px' : '16px',
      zIndex: '260',
      width: window.innerWidth <= 760 ? '248px' : (pane.style.width || '260px'),
      maxWidth: window.innerWidth <= 760 ? 'calc(100vw - 24px)' : 'min(300px, calc(100vw - 32px))',
      display: 'block',
    })
  })
}

function updateAnalytics(dt) {
  const info = renderer.webgl.info
  const renderInfo = info.render
  const memoryInfo = info.memory

  analytics.fps.textContent = currentFps ? `${currentFps} fps` : '--'
  analytics.frame.textContent = `${(dt * 1000).toFixed(1)} ms`
  analytics.draws.textContent = `${renderInfo.calls} render passes`
  analytics.geo.textContent = `${memoryInfo.geometries} shapes, ${memoryInfo.textures} textures`
  analytics.scene.textContent = `${renderer.scene.children.length} visible parts`
  analytics.camera.textContent = formatVec3(renderer.camera.position)
  analytics.pointer.textContent = `${renderer._mouse.x.toFixed(2)}, ${renderer._mouse.y.toFixed(2)}`
  analytics.audio.textContent = audio.enabled
    ? `bass ${audio.bass.toFixed(2)}, mid ${audio.mid.toFixed(2)}, high ${audio.treble.toFixed(2)}`
    : 'off'
  analytics.bloom.textContent = `${renderer.bloomPass.strength.toFixed(2)}`
  analytics.viewport.textContent = `${window.innerWidth} x ${window.innerHeight}`
}

setModeChrome('lissajous')
updateAudioChrome()
setControlsVisible(true)
requestAnimationFrame(positionControlPane)

// ---------------------------------------------------------------------------
// Click → ripple distortion
// ---------------------------------------------------------------------------

window.addEventListener('click', e => {
  // Don't trigger inside the nav or control panels
  if (e.target.closest('#nav, #hud, #toast, #analytics-panel, .tp-dfwv')) return
  renderer.triggerRipple(e.clientX, e.clientY)
})

// ---------------------------------------------------------------------------
// Audio toggle button (added programmatically to keep index.html minimal)
// ---------------------------------------------------------------------------

// ── Mic toggle ──────────────────────────────────────────────────────────────
const audioBtn = document.createElement('button')
audioBtn.textContent = 'Mic'
audioBtn.className   = 'nav-btn'
audioBtn.id          = 'audio-btn'
Object.assign(audioBtn.style, { marginLeft: '4px' })
document.getElementById('nav').appendChild(audioBtn)

audioBtn.addEventListener('click', async () => {
  // If a file track is loaded, just toggle enabled state without reopening mic
  if (audio._source && audio._source.buffer !== undefined) {
    // File source active — suspend / resume instead
    if (audio.enabled) {
      audio.enabled = false
      audio._ctx?.suspend()
    } else {
      audio.enabled = true
      audio._ctx?.resume()
    }
  } else {
    await audio.toggle()
  }
  audioBtn.classList.toggle('active', audio.enabled)
  activeMode.setAudio?.(audio)
  updateAudioChrome()
})

// ── Track loader — hidden file input + nav button ────────────────────────────
const trackInput = document.createElement('input')
trackInput.type   = 'file'
trackInput.accept = 'audio/*'
trackInput.style.display = 'none'
document.body.appendChild(trackInput)

const trackBtn = document.createElement('button')
trackBtn.textContent = 'Track'
trackBtn.className   = 'nav-btn'
Object.assign(trackBtn.style, { marginLeft: '1px' })
document.getElementById('nav').appendChild(trackBtn)

trackBtn.addEventListener('click', () => trackInput.click())

trackInput.addEventListener('change', async () => {
  const file = trackInput.files?.[0]
  if (!file) return
  trackBtn.textContent = file.name.replace(/\.[^.]+$/, '')  // strip extension
  await audio.enableFromFile(file)
  trackBtn.classList.add('active')
  audioBtn.classList.add('active')
  activeMode.setAudio?.(audio)
  updateAudioChrome()
  showToast(`Loaded ${file.name}`)
})

hud.controls.addEventListener('click', () => {
  setControlsVisible(!controlsVisible)
  showToast(controlsVisible ? 'Controls visible' : 'Controls hidden')
})

hud.controlsHandle.addEventListener('click', () => {
  setControlsVisible(!controlsVisible)
  showToast(controlsVisible ? 'Controls visible' : 'Controls hidden')
})

hud.analytics.addEventListener('click', () => {
  setAnalyticsVisible(!analyticsVisible)
  showToast(analyticsVisible ? 'Analytics visible' : 'Analytics hidden')
})

hud.pause.addEventListener('click', () => {
  paused = !paused
  hud.pause.classList.toggle('active', paused)
  hud.pause.textContent = paused ? 'GO' : 'II'
  hud.pause.setAttribute('aria-label', paused ? 'Resume animation' : 'Pause animation')
  hud.pause.setAttribute('title', paused ? 'Resume animation' : 'Pause animation')
  showToast(paused ? 'Animation paused' : 'Animation resumed')
})

hud.capture.addEventListener('click', () => {
  renderer.render()
  const link = document.createElement('a')
  const mode = (hud.mode.textContent || 'math-vis').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  link.download = `${mode || 'math-vis'}-${new Date().toISOString().slice(0, 10)}.png`
  link.href = renderer.domElement.toDataURL('image/png')
  link.click()
  showToast('Saved PNG snapshot')
})

hud.fullscreen.addEventListener('click', async () => {
  try {
    if (!document.fullscreenElement) {
      await document.documentElement.requestFullscreen()
      hud.fullscreen.classList.add('active')
    } else {
      await document.exitFullscreen()
      hud.fullscreen.classList.remove('active')
    }
  } catch {
    showToast('Fullscreen is blocked by this browser')
  }
})

document.addEventListener('fullscreenchange', () => {
  hud.fullscreen.classList.toggle('active', Boolean(document.fullscreenElement))
})

// ---------------------------------------------------------------------------
// Cursor
// ---------------------------------------------------------------------------

const cursorDot  = document.getElementById('cursor-dot')
const cursorRing = document.getElementById('cursor-ring')

// Both dot and ring follow the cursor instantly — the ring must stay
// pixel-aligned with the WebGL lens shader which uses the raw cursor UV.
window.addEventListener('mousemove', e => {
  gsap.set(cursorDot,  { x: e.clientX, y: e.clientY })
  gsap.set(cursorRing, { x: e.clientX, y: e.clientY })
})

// ---------------------------------------------------------------------------
// Nav buttons — split text + magnetic + bloom cursor reaction
// ---------------------------------------------------------------------------

const navBtns = document.querySelectorAll('.nav-btn:not(.soon)')

navBtns.forEach(btn => {
  // ── 1. Split text into individual character <span>s ──────────────────────
  // This lets GSAP animate each letter independently (stagger).
  const chars = [...btn.textContent].map(ch => {
    const s = document.createElement('span')
    s.textContent = ch === ' ' ? '\u00a0' : ch
    s.style.cssText = 'display:inline-block; will-change:transform'
    return s
  })
  btn.textContent = ''
  chars.forEach(s => btn.appendChild(s))

  // ── 2. Character wave on hover ────────────────────────────────────────────
  // Each char lifts then returns, staggered left-to-right.
  btn.addEventListener('mouseenter', () => {
    gsap.to(chars, {
      y:        -4,
      duration: 0.22,
      ease:     'power2.out',
      stagger:  0.025,
      yoyo:     true,
      repeat:   1,
    })
  })

  btn.addEventListener('mouseleave', () => {
    gsap.killTweensOf(chars)
    gsap.to(chars, { y: 0, duration: 0.3, ease: 'power2.out', stagger: 0.015 })
  })

  // ── 3. Magnetic pull ──────────────────────────────────────────────────────
  // As the cursor moves over the button, the button shifts toward the cursor.
  // On leave it snaps back with elastic physics — the overshoot is what
  // makes it feel physical rather than computed.
  btn.addEventListener('mousemove', e => {
    const rect = btn.getBoundingClientRect()
    const dx   = e.clientX - (rect.left + rect.width  / 2)
    const dy   = e.clientY - (rect.top  + rect.height / 2)
    gsap.to(btn, {
      x:        dx * 0.28,
      y:        dy * 0.28,
      duration: 0.35,
      ease:     'power2.out',
    })
  })

  btn.addEventListener('mouseleave', () => {
    // elastic.out(amplitude, period) — overshoot then settle
    gsap.to(btn, { x: 0, y: 0, duration: 0.9, ease: 'elastic.out(1, 0.45)' })
  })

  // ── 4. Click ──────────────────────────────────────────────────────────────
  btn.addEventListener('click', () => {
    if (!btn.dataset.mode) return   // skip non-mode buttons (e.g. audio toggle)
    if (btn.classList.contains('active') || transitioning) return
    navBtns.forEach(b => b.classList.remove('active'))
    btn.classList.add('active')
    switchTo(btn.dataset.mode)
  })
})

// ---------------------------------------------------------------------------
// Mode switching — choreographed GSAP timeline
// ---------------------------------------------------------------------------

function switchTo(name) {
  transitioning = true
  setModeChrome(name, true)

  // ── Phase 1: exit current scene ───────────────────────────────────────────
  const exitTl = gsap.timeline({
    onComplete: () => enterScene(name),
  })

  // Bloom flare + chroma split signal the cut
  exitTl
    .to(renderer.bloomPass, {
      strength: 3.2,
      duration: 0.18,
      ease:     'power3.in',
    }, 0)
    .to(renderer.chromaPass.uniforms.uStrength, {
      value:    0.006,
      duration: 0.18,
      ease:     'power3.in',
    }, 0)
    .to(overlay, {
      opacity:  1,
      duration: 0.22,
      ease:     'power2.in',
    }, 0)
}

function enterScene(name) {
  activeMode.dispose()
  renderer.scene.clear()

  switch (name) {
    case 'lissajous':  activeMode = new LissajousMode(renderer.scene, renderer);  break
    case 'fourier':    activeMode = new FourierMode(renderer.scene, renderer);    break
    case 'rose':       activeMode = new RoseMode(renderer.scene, renderer);       break
    case 'chaos':      activeMode = new ChaosMode(renderer.scene, renderer);      break
    case 'mandelbrot': activeMode = new MandelbrotMode(renderer.scene, renderer); break
    case 'pendulum':   activeMode = new PendulumMode(renderer.scene, renderer);   break
    case 'newton':     activeMode = new NewtonMode(renderer.scene, renderer);     break
    case 'grayscott':  activeMode = new GrayScottMode(renderer.scene, renderer);  break
    case 'julia':      activeMode = new JuliaMode(renderer.scene, renderer);      break
  }

  requestAnimationFrame(positionControlPane)

  // Re-add particles to the scene (scene.clear() removed them)
  renderer.scene.add(particles._pointsBlue)
  renderer.scene.add(particles._pointsAmber)

  // Pass audio to modes that support it
  activeMode.setAudio?.(audio)

  // Hide particles in pure-2D locked-camera modes (they'd be behind the quad)
  const is2D = (name === 'mandelbrot' || name === 'fourier' || name === 'newton' || name === 'grayscott' || name === 'julia')
  particles.setVisible(!is2D)

  // ── Phase 2: enter new scene ──────────────────────────────────────────────
  const enterTl = gsap.timeline({
    onComplete: () => { transitioning = false },
  })

  enterTl
    .to(overlay, { opacity: 0, duration: 0.5, ease: 'power2.out' }, 0)
    .to(renderer.bloomPass, { strength: 1.0, duration: 1.4, ease: 'power3.out' }, 0)
    .to(renderer.chromaPass.uniforms.uStrength, { value: 0.0006, duration: 1.0, ease: 'power2.out' }, 0)
}

// ---------------------------------------------------------------------------
// Resize
// ---------------------------------------------------------------------------

window.addEventListener('resize', () => {
  if (activeMode.onResize) activeMode.onResize()
  positionControlPane()
})

// ---------------------------------------------------------------------------
// Animation loop
// ---------------------------------------------------------------------------

function tick() {
  requestAnimationFrame(tick)
  const now = performance.now()
  const dt  = Math.min((now - prevTime) / 1000, 0.05)
  prevTime  = now
  fpsFrames += 1

  if (now - fpsSampleTime > 500) {
    currentFps = Math.round((fpsFrames * 1000) / (now - fpsSampleTime))
    hud.fps.textContent = `${currentFps} fps`
    fpsFrames = 0
    fpsSampleTime = now
  }

  // Audio — read FFT every frame
  if (!paused) audio.update()

  // Bloom responds to audio overall amplitude — but only in modes that use bloom.
  // Mandelbrot disables bloom entirely (bloomPass.strength = 0) to prevent
  // the fractal exterior from washing out to white.
  if (audio.enabled && renderer.bloomPass.strength > 0) {
    renderer.bloomPass.strength = 1.0 + audio.overall * 0.8
  }

  // Particle field — cursor NDC from renderer's internal mouse tracker
  if (!paused) {
    particles.update(dt, renderer._mouse)

    activeMode.update(dt)
  }
  renderer.render()

  if (analyticsVisible && now - analyticsSampleTime > 180) {
    updateAnalytics(dt)
    analyticsSampleTime = now
  }
}

tick()
